# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./Backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd Backend; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DB_USER=alantodo
      - DB_PASS=alantodo
      - DB_HOST=db
      - DB_NAME=todo
    depends_on:
      - db
  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=alantodo
      - POSTGRES_PASSWORD=alantodo
      - POSTGRES_DB=todo

volumes:
  postgres_data:
